service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: epam-h4v3u
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - https://d2smauulytlpo1.cloudfront.net

functions:
  getProductsList:
    handler: lambda/getProductsList/index.handler
    events:
      - httpApi:
          path: /products
          method: get

  getProductsById:
    handler: lambda/getProductsById/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: get
